// src/types/api.d.ts

import type { Vehicle, Driver, State, YesNo } from "./covercube";

/**
 * Input for /api/quote endpoint
 * Mirrors CovercubeRequest but excludes fields auto-generated by backend
 * (auth credentials, action type, producer code)
 */
export interface QuoteInput {
  // Transaction details
  policyTerm: string;
  inceptionDate: string;
  effectiveDate: string;
  rateDate: string;
  
  // Policyholder info
  holderFirstName: string;
  holderMiddleInitial?: string;
  holderLastName: string;
  address: string;
  address2?: string;
  city: string;
  state: State;
  zipCode: string;
  email?: string;
  cellPhone?: string;
  mailSame?: YesNo;
  mailAddress?: string;
  mailAddress2?: string;
  mailCity?: string;
  mailState?: string;
  mailZipCode?: string;
  
  // Coverage
  BI: string;
  PD: string;
  UMBI?: string;
  UIMBI?: string;
  UMPD?: string; // TX only
  MP?: string;
  PIP?: string; // TX only
  roadsideAssistance?: YesNo;
  
  // Discounts & flags
  unacceptableRisk?: YesNo;
  renewalDiscount?: YesNo;
  advanceDiscount?: YesNo;
  homeownerDiscount?: YesNo;
  payplan: string;
  
  // Prior insurance
  ispriorpolicy?: "YES" | "NO";
  priorpolicynumber?: string;
  priordayslapse?: number | string;
  priorexpirationdate?: string;
  monthsinprior?: number | string;
  ispriorinsameagency?: "YES" | "NO";
  priorbicoveragelimit?: string;
  priorpipcoveragelimit?: number;
  
  // Non-owner flag (TX only)
  IsNonOwner?: YesNo;
  
  // Arrays
  vehicles?: Vehicle[];
  drivers: Driver[];
}